//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectooo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alojamiento_has_tipo_alojamineto
    {
        public int Id { get; set; }
        public int AlojamientoId { get; set; }
        public int Tipo_alojamientoId { get; set; }
    
        public virtual Alojamiento Alojamiento { get; set; }
        public virtual Tipo_alojamiento Tipo_alojamiento { get; set; }
    }
}
